spring.profiles.active: docker1
server:
 port: 9114
spring:
 application:
  name: contract-consumer-service
---
spring:
  profiles: docker1
  cloud:
    stream:
      bindings:
        contractRequestChannel:
          destination: contractRequestTopic
          content-type: application/json
        flowChannel:
          destination: flowTopic
          content-type: application/json
        historialChannel:
          destination: historialTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: 10.100.21.238
          brokers: 10.100.21.238
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
  datasource:
   url: jdbc:mysql://10.100.21.238:3306/queries
   username: root
   password: dbpass
eureka:
  instance:
    prefer-ip-address: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.100.21.238:8761/eureka/,http://10.100.21.238:8762/eureka/
      
logging:
 file: /opt/apps/logs/contract-consumer.log
---
spring:
  profiles: docker2
  cloud:
    stream:
      bindings:
        input:
          destination: contractRequestTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: 10.100.21.238
          brokers: 10.100.21.238
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
  datasource:
   url: jdbc:mysql://10.100.21.238:3306/queries
   username: root
   password: dbpass
eureka:
  instance:
    prefer-ip-address: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.100.21.238:8761/eureka/,http://10.100.21.238:8762/eureka/
      
logging:
 file: /opt/apps/logs/contract-consumer.log
server:
 port: 9115
---
spring:
  profiles: nodocker
  cloud:
    stream:
      bindings:
        contractRequestChannel:
          destination: contractRequestTopic
          content-type: application/json
          group: contractRequestConsumer
      kafka:
        binder:
          zkNodes: 10.100.21.238
          brokers: 10.100.21.238
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create-drop
    show-sql: true
  datasource:
   url: jdbc:mysql://10.100.21.238:3306/queries
   username: root
   password: dbpass
eureka:
  instance:
    prefer-ip-address: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.100.21.238:8761/eureka/,http://10.100.21.238:8762/eureka/
      
logging:
 file: /opt/apps/logs/contract-consumer.log
server:
 port: 9115