spring.profiles.active: docker1
server:
 port: 9114
spring:
 application:
  name: contract-consumer-service
---
spring:
  profiles: docker1
  cloud:
    stream:
      bindings:
        contractRequestChannel:
          destination: cr-topic
          content-type: application/json
          group: cr-consumer
        flowChannel:
          destination: flow-topic
          content-type: application/json
          group: flow-consumer
        historialChannel:
          destination: historial-topic
          content-type: application/json
          group: historial-consumer
      kafka:
        binder:
          zkNodes: 10.100.21.238
          brokers: 10.100.21.238
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    show-sql: true
  datasource:
   url: jdbc:mysql://10.100.21.238:3306/queries
   username: root
   password: dbpass
eureka:
  instance:
    prefer-ip-address: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.100.21.238:8761/eureka/,http://10.100.21.238:8762/eureka/
      
logging:
 file: /opt/apps/logs/contract-consumer.log
spring.cloud.stream.kafka.binder.configuration.auto.offset.reset: earliest
spring.cloud.stream.kafka.bindings.flowChannel.consumer.startOffset: earliest