spring.profiles.active: local
info:
  version: @project.version@
endpoints:
  shutdown:
    enabled: true
---
spring:
  profiles: local
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: discovery1
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka/
logging:
 file: /opt/apps/logs/discovery1_service.log
---
spring:
  profiles: discovery2
server:
  port: 8762
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/
logging:
 file: /opt/apps/logs/discovery1_service.log
---
spring:
  profiles: docker
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka/
logging:
 file: /opt/apps/logs/discovery_service.log