spring.profiles.active: local
info:
  version: @project.version@
endpoints:
  shutdown:
    enabled: true
---
spring:
  profiles: local
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: discovery1
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka/
logging:
 file: /opt/apps/logs/discovery1_service.log
---
spring:
  profiles: discovery2
server:
  port: 8762
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/
logging:
 file: /opt/apps/logs/discovery1_service.log
---
spring:
  profiles: docker1
server:
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/,http://discovery-service-replica:8762/eureka
logging:
 file: /opt/apps/logs/${HOSTNAME}.log
---
spring:
  profiles: docker2
server:
  port: 8762
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/,http://discovery-service-replica:8762/eureka
logging:
 file: /opt/apps/logs/${HOSTNAME}.log