spring:
  profiles:
    active: development   
server:
  port: 9999
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user-query-service: /user/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user-query-service: /user/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
